FROM tensorflow/tensorflow:2.1.0-py3 as builder

RUN pip3 install --upgrade --no-cache \
  setuptools click numpy pandas pathlib seaborn sklearn

FROM builder

WORKDIR /usr/src

EXPOSE 5000

COPY ./requirements.txt .
RUN pip3 install -r requirements.txt

ENV FLASK_APP=wsgi.py
ENV APP_CONFIG_FILE=config.py
ENV FLASK_DEBUG=0

CMD ["flask", "run", "--host=0.0.0.0"]