version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src
    ports:
      - 3000:3000
    environment:
      FLASK_ENV: development
      HOSTNAME: 0.0.0.0
      PORT: 3000
      SECRET_KEY:
      CLIENT_ID:
      CLIENT_SECRET:
      CALLBACK: https://b435fdb1.ngrok.io/oauth/callback
      REDIS: redis://redis:6379
    depends_on:
      - redis
  redis:
    image: redis
    entrypoint: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    restart: always

volumes:
  redis-data: ~