version: '3'
services:
  app:
    build: .
    volumes:
      - .:/usr/src
    ports:
      - 3000:3000
    environment:
      FLASK_ENV: development
      HOSTNAME: 0.0.0.0
      PORT: 3000
      SECRET_TOKEN:
      CLIENT_ID:
      CLIENT_SECRET:
      CALLBACK: https://b435fdb1.ngrok.io/oauth/callback