FROM python:3.7-alpine

WORKDIR /usr/src

EXPOSE 5000

COPY ./requirements.txt .

RUN pip install -r requirements.txt

COPY . .

ENV FLASK_APP=wsgi.py
ENV APP_CONFIG_FILE=config.py
ENV FLASK_DEBUG=1

CMD ["flask", "run", "--host=0.0.0.0"]