name: Build and Deploy

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Login
        uses: sjdonado/heroku@master
        with:
          args: container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      - name: Push
        uses: sjdonado/heroku@master
        with:
          args: container:push -a $(basename $GITHUB_REPOSITORY) web
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      - name: Release
        uses: sjdonado/heroku@master
        with:
          args: container:release -a $(basename $GITHUB_REPOSITORY) web
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}